version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:8001"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - postgres
        networks: 
            - laravel

    postgres:
        image: postgres:14.1-alpine
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:5432"
        volumes: 
            - ./db:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: laravel_docker
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel
